---
# tasks file for ansible-tensorflow

    - name: Ensure git is installed
      apt: pkg=git state=installed

    - name: Pull Tensorflow Examples from github
      git:
       repo: https://github.com/DeepLearningDTU/02456-deep-learning.git
       dest: /home/ubuntu/deep_learning
       force: yes
       update: yes

    - name: Install all the packages listed in requirements.txt
      shell: sudo pip3 install -r /home/ubuntu/deep_learning/requirements.txt

    - name: Change ownership
      shell: sudo chown -R ubuntu /home/ubuntu/deep_learning
