---
# tasks file for ansible-tensorflow

    #Bazel
    - apt_repository: repo='deb http://storage.googleapis.com/bazel-apt stable jdk1.8' state=present
    - apt_key: url=https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg state=present
    - apt: update_cache=yes
    - apt: name=bazel state=installed

    - name: install tensorflow
      command: "sudo pip3 install --upgrade {{item}}"
      with_items:
        #- tensorflow
        - tensorflow-gpu==1.2.0
        - tflearn
        - keras
        #- theano
        #- lasagne
        #- gpustat
        #- scikit-image
