 - apt_repository: repo='ppa:fkrull/deadsnakes' state=present
   when: ansible_distribution in [ 'Ubuntu' ]

 - apt_key: id=C7917B12 keyserver=keyserver.ubuntu.com
   when: ansible_distribution in [ 'Ubuntu' ]

 - name: Ensure Basic Packages installed
   apt: pkg={{ item }} state=installed
   with_items:
   - python3.5
   - python3.5-dev
   - libncurses5-dev
   - python3-pip
   - python3-dev
   - libpq-dev
   - supervisor

 - name: download foo.conf
   get_url: url=https://bootstrap.pypa.io/get-pip.py
      dest=/usr/local/get-pip.py mode=0644

 - name: create pip3
   command: python3 /usr/local/get-pip.py
    creates=/usr/local/bin/pip3

 - name: install setuptools with pip3
   command: pip3 install setuptools --upgrade

 - name: install scientific python packages
   command: "pip3 install --upgrade {{item}}"
   with_items:
     - ipython[all]
     - jupyter[all]
     - jupyter_core
     - jinja2
     - zmq
     - tornado
     - jsonschema
     - matplotlib
     - Cython
     - pandas
     - numpy
     - scikit-learn
     - scipy
     - seaborn
     - scikit-image
