---
# tasks file for ansible-tensorflow

    #Bazel
    - apt_repository: repo='deb http://storage.googleapis.com/bazel-apt stable jdk1.8' state=present
    - apt_key: url=https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg state=present
    - apt: update_cache=yes
    - apt: name=bazel state=installed

    - name: install tensorflow
      command: "sudo pip3 install --upgrade {{item}}"
      with_items:
        #- tensorflow
        - tensorflow-gpu==1.3.0
        - tflearn
        - keras
        - theano
        - lasagne
        - gym
        - git+https://github.com/jakevdp/JSAnimation.git
        - gpustat
        #- scikit-image

    - name: Create gtop alias
      lineinfile:
        dest=/home/ubuntu/.bashrc
        line="alias gtop='watch --color -n 1.0 gpustat'"
        owner=ubuntu
