---
# tasks file for ansible-cudnn

    # install CUDA Toolkit v8.0
    # instructions from https://developer.nvidia.com/cuda-downloads (linux -> x86_64 -> Ubuntu -> 16.04 -> deb (network))
    - name: Download CUDA 8.0
      get_url:
        url="https://developer.nvidia.com/compute/cuda/8.0/Prod2/local_installers/cuda-repo-ubuntu1604-8-0-local-ga2_8.0.61-1_amd64-deb"
        dest="/tmp/{{CUDA_REPO_PKG}}"

    - name: Depackage CUDA 8.0
      sudo: yes
      command: "dpkg -i /tmp/{{CUDA_REPO_PKG}}"

    - name: Update apt-get
      sudo: yes
      command: "apt-get update"

    - name: Install CUDA 8.0
      sudo: yes
      command: "apt-get -y install cuda --allow-unauthenticated"

    - name: Download CUDNN 6.0
      get_url:
        url="http://developer.download.nvidia.com/compute/redist/cudnn/v6.0/cudnn-8.0-linux-x64-v6.0.tgz"
        dest="/tmp/cudnn-8.0-linux-x64-v6.0.tgz"

    - name: untar cuDNN
      sudo: true
      command: "tar -xzvf /tmp/cudnn-8.0-linux-x64-v6.0.tgz -C /tmp"
      args:
        creates: /tmp/cuda

    - name: Copy cuDNN headers from /tmp/cuda
      command: "cp /tmp/cuda/include/cudnn.h /usr/local/cuda/include"
      args:
        creates: /usr/local/cuda/include/cudnn.h

    - name: Copy cuDNN libs from /tmp/cuda
      shell: "cp /tmp/cuda/lib64/libcudnn* /usr/local/cuda/lib64/"
      args:
        creates: /usr/local/cuda/lib64/libcudnn.so.6

    - name: Set permissions on cuDNN files
      shell: "chmod a+r /usr/local/cuda/include/cudnn.h /usr/local/cuda/lib64/libcudnn*"

    - name: Append to path
      shell: "export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}"
      shell: "export LD_LIBRARY_PATH=/usr/local/cuda/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

    - name: Append to .bashrc
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: "export PATH=/usr/local/cuda/bin${PATH:+:${PATH}}"

    - name: Another Append
      lineinfile:
        path: /home/ubuntu/.bashrc
        line: "export LD_LIBRARY_PATH=/usr/local/cuda/lib${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"

    - name: Source .bashrc
      sudo: no
      shell: source /home/ubuntu/.bashrc
      args:
         executable: /bin/bash

    - name: Install list of packages
      apt: name={{item}} state=installed
      with_items:
        - opencl-headers
        - build-essential
        - protobuf-compiler
        - libprotoc-dev
        - libboost-all-dev
        - libleveldb-dev
        - hdf5-tools
        - libhdf5-serial-dev
        - libopencv-core-dev
        - libopencv-highgui-dev
        - libsnappy-dev
        - libatlas-base-dev
        - cmake
        - libstdc++6-4.8-dbg
        - libgoogle-glog-dev
        - libgflags-dev
        - liblmdb-dev
        - gfortran
        - htop


